package pipedrive

type UsersService service

type AutoGenerated struct {
	Success bool `json:"success"`
	Data    []struct {
		ID                  int         `json:"id"`
		Name                string      `json:"name"`
		DefaultCurrency     string      `json:"default_currency"`
		Locale              string      `json:"locale"`
		Lang                int         `json:"lang"`
		Email               string      `json:"email"`
		Phone               interface{} `json:"phone"`
		Activated           bool        `json:"activated"`
		LastLogin           string      `json:"last_login"`
		Created             string      `json:"created"`
		Modified            string      `json:"modified"`
		SignupFlowVariation string      `json:"signup_flow_variation"`
		HasCreatedCompany   bool        `json:"has_created_company"`
		IsAdmin             int         `json:"is_admin"`
		TimezoneName        string      `json:"timezone_name"`
		TimezoneOffset      string      `json:"timezone_offset"`
		ActiveFlag          bool        `json:"active_flag"`
		RoleID              int         `json:"role_id"`
		IconURL             interface{} `json:"icon_url"`
		IsYou               bool        `json:"is_you"`
	} `json:"data"`
	AdditionalData struct {
		CompanyID int `json:"company_id"`
	} `json:"additional_data"`
}
